
image: "rust:latest"

stages:
  - build
  - test
  - deploy
  - post-run

cache:
  key: "${CI_JOB_NAME}"
  paths:
    - ${CI_PROJECT_DIR}/target/

clean-code:
  stage: build
  script:
    - rustup component add rustfmt-preview
    - cargo fmt --all -- --check
  allow_failure: true

build-noughts-and-crosses-game:
  stage: build
  script:
    - rustup default nightly
    - rustup update
    - (cd noughts-and-crosses-game && cargo build)

build-noughts-and-crosses-lib:
  stage: build
  script:
    - rustup default nightly
    - rustup update
    - (cd noughts-and-crosses-lib && cargo build)

build-ai-graph:
  stage: build
  script:
    - rustup default nightly
    - rustup update
    - (cd ai-graph && cargo build)

build-noughts-and-crosses-ai-test:
  stage: build
  script:
    - rustup default nightly
    - rustup update
    - (cd noughts-and-crosses-ai-test && cargo build)

build-noughts-and-crosses-random-train:
  stage: build
  script:
    - rustup default nightly
    - rustup update
    - (cd noughts-and-crosses-random-train && cargo build)

unittests:
  stage: test
  script:
    - rustup default nightly
    - rustup update
    - cargo test

benchmarktests:
  stage: test
  script:
    - rustup default nightly
    - rustup update
    - cargo bench


nightly-linux-optimized:
  stage: deploy
  cache: {}
  script:
    - apt-get update
    - rustup default nightly
    - rustup update
    - (cd noughts-and-crosses-game && cargo build --release)
    - (cd ai-graph && cargo build --release)
    - (cd noughts-and-crosses-lib && cargo build --release)
    - cp target/release/noughts-and-crosses-game noughts-and-crosses-game
  when: always
  artifacts:
    paths:
      - noughts-and-crosses-game
    expire_in: 6 months
  only:
    refs:
      - master
      - dev

nightly-windows-optimized:
  stage: deploy
  script:
    - apt-get update
    - rustup default nightly
    - rustup update
    - apt-get install gcc -y
    - apt-get install zip -y
    - apt-get install gcc-mingw-w64-x86-64 -y
    - apt-get install libsdl2-dev -y
    - wget https://www.libsdl.org/release/SDL2-devel-2.0.4-mingw.tar.gz -P /tmp
    - tar xf /tmp/SDL2-devel-2.0.4-mingw.tar.gz -C /tmp
    - rustup component add rust-std --target=x86_64-pc-windows-gnu
    - mkdir .cargo
    - touch .cargo/config
    - echo [target.x86_64-pc-windows-gnu] >> .cargo/config
    - echo     linker = \"x86_64-w64-mingw32-gcc\" >> .cargo/config
    - echo     ar = \"x86_64-w64-mingw32-gcc-ar\" >> .cargo/config
    - cat .cargo/config
    - (cd noughts-and-crosses-game && cargo build --release --target=x86_64-pc-windows-gnu)
    - (cd ai-graph && cargo build --release --target=x86_64-pc-windows-gnu)
    - (cd noughts-and-crosses-lib && cargo build --release --target=x86_64-pc-windows-gnu)
    - rm -r -f nightly
    - mkdir nightly
    # - cp target/x86_64-pc-windows-gnu/release/ai-graph.exe nightly
    - cp target/x86_64-pc-windows-gnu/release/noughts-and-crosses-game.exe nightly
    # - cp target/x86_64-pc-windows-gnu/release/noughts-and-crosses-lib.exe nightly
    - rm -f nightly-windows-optimized.zip
    - zip -r nightly-windows-optimized.zip nightly
  when: always
  artifacts:
    paths:
      - nightly-windows-optimized.zip
    expire_in: 6 months
  only:
    refs:
      - master
      - dev


clippy:
  stage: post-run
  script:
    - rustup default nightly
    - rustup update
    - rustup component add clippy-preview
    - cargo clippy --all -- -D clippy::all
  allow_failure: true
