[package]
name = "gui"
version = "0.1.0"
authors = ["Ethan Brierley <ethanboxx@gmail.com>"]
readme = "README.md"
repository = "https://gitlab.com/efunb/rustGame"
description = """
RustGame.
"""
[dependencies]
conrod = "0.61"



