[package]
name = "ai-graph"
version = "0.0.1"
authors = ["Ethan Brierley <ethanboxx@gmail.com>"]
license = "MIT/Apache-2.0"
repository = "https://gitlab.com/efunb/noughts-and-crosses-ai-collection"
edition = '2018'

[dependencies]
rand = "0.5"